version: '2'

services:
    nginx:
        image: nginx:1.13.5
        ports:
            - 8023:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - python

    python:
        build: ./docker/python/
        expose:
            - 9000
        volumes:
            - .:/var/www/html
        command: /bin/bash -c "pip install -r requirements.txt && gunicorn -b :9000 --reload app:app"